#ifndef API_H 
#define API_H

#include "params.h"

#include "pq_api.h"

#define CRYPTO_ALGNAME "NTRU-KEM-HRSS17"

#define CRYPTO_SECRETKEYBYTES NTRU_SECRETKEYBYTES
#define CRYPTO_PUBLICKEYBYTES NTRU_PUBLICKEYBYTES
#define CRYPTO_CIPHERTEXTBYTES NTRU_CIPHERTEXTBYTES
#define CRYPTO_BYTES NTRU_SHAREDKEYBYTES

#endif
